# Generated by Django 4.2.9 on 2024-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=9, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("week_growth", models.FloatField()),
                ("five_year_growth", models.FloatField()),
                (
                    "cap_size",
                    models.CharField(
                        choices=[("s", "small"), ("m", "medium"), ("l", "large")],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
