# Generated by Django 4.2.9 on 2024-02-01 16:55

from django.db import migrations, models
import stocks.models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_userstocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstocks",
            name="shares",
            field=models.FloatField(
                default=0, validators=[stocks.models.non_negative_validator]
            ),
        ),
    ]
