FROM node:lts-alpine as builder

WORKDIR /app

COPY . .

RUN npm i
RUN npm run build

FROM nginx:alpine-slim

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

WORKDIR /usr/share/nginx/html

RUN apk add --no-cache bash