# Generated by Django 4.2.9 on 2024-01-28 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_id_user_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="uuid",
            new_name="id",
        ),
    ]
