# Generated by Django 4.2.9 on 2024-01-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_uuid_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
