# Generated by Django 4.2.9 on 2024-02-01 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_userportfolioactual"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPortfolioActual",
        ),
    ]
